# Generated by Django 2.1.3 on 2018-11-23 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MensagensPadrao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mensagem', models.CharField(max_length=255, verbose_name='mensagem')),
                ('resposta', models.CharField(max_length=255, verbose_name='resposta')),
            ],
        ),
    ]
