# Generated by Django 2.1.3 on 2018-11-26 15:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bot_facebook', '0001_initial'),
        ('bot_telegram', '0001_initial'),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Aventura',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50, verbose_name='Nome')),
                ('descricao', models.TextField(blank=True, verbose_name='Descrição')),
            ],
            options={
                'verbose_name': 'Aventura',
                'verbose_name_plural': 'Aventuras',
            },
        ),
        migrations.CreateModel(
            name='Cena',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50, verbose_name='Nome')),
                ('descricao', models.TextField(blank=True, verbose_name='Descrição')),
                ('numero', models.PositiveSmallIntegerField(verbose_name='Ordem')),
                ('aventura', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Aventura', verbose_name='Aventura')),
            ],
            options={
                'verbose_name': 'Cena',
                'verbose_name_plural': 'Cenas',
            },
        ),
        migrations.CreateModel(
            name='Opcao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.TextField(blank=True, verbose_name='Descrição')),
                ('proxima_cena', models.PositiveSmallIntegerField(verbose_name='Proxima Cena')),
                ('cena', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Cena', verbose_name='Cena')),
            ],
            options={
                'verbose_name': 'Opção',
                'verbose_name_plural': 'Opções',
            },
        ),
        migrations.CreateModel(
            name='Personagem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cena', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Cena')),
                ('nome', models.CharField(max_length=50, verbose_name='Nome')),
                ('iniciou', models.DateTimeField(auto_now_add=True, verbose_name='Iniciou')),
                ('ultimo_acesso', models.DateTimeField(auto_now=True, verbose_name='Ultimo Acesso')),
                ('genero', models.IntegerField(blank=True, choices=[(0, 'Homem'), (1, 'Mulher'), (2, 'Outro')], default=0, verbose_name='Genero')),
                ('aventura', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Aventura', verbose_name='Aventura')),
                ('jogadorF', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bot_facebook.Jogadores', verbose_name='Jogador Facebook')),
                ('jogadorT', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bot_telegram.Jogadores', verbose_name='Jogador Telegram')),
            ],
            options={
                'verbose_name': 'Personagem',
                'verbose_name_plural': 'Personagens',
            },
        ),
    ]
