# Generated by Django 2.1.3 on 2018-11-27 12:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_aventura_cena_opcao_personagem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='opcao',
            name='cena',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='OpcaoCena', to='core.Cena', verbose_name='Cena'),
        ),
        migrations.AlterField(
            model_name='opcao',
            name='proxima_cena',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='OpcaoProximaCena', to='core.Cena', verbose_name='Próxima Cena'),
        ),
    ]
