# Generated by Django 2.1.3 on 2018-11-27 15:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20181127_1024'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='personagem',
            name='cena',
        ),
        migrations.AddField(
            model_name='personagem',
            name='cena_atual',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.Cena', verbose_name='Cena Atual'),
        ),
    ]
