# Generated by Django 2.1.3 on 2018-11-27 16:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20181127_1359'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personagem',
            name='jogadorF',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='bot_facebook.Jogadores', verbose_name='Jogador Facebook'),
        ),
        migrations.AlterField(
            model_name='personagem',
            name='jogadorT',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='bot_telegram.Jogadores', verbose_name='Jogador Telegram'),
        ),
    ]
