# Generated by Django 2.1.3 on 2018-11-27 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot_facebook', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='jogadores',
            options={'verbose_name': 'Jogador', 'verbose_name_plural': 'Jogadores'},
        ),
        migrations.RemoveField(
            model_name='jogadores',
            name='nome',
        ),
        migrations.AddField(
            model_name='jogadores',
            name='primeiro_nome',
            field=models.CharField(blank=True, max_length=50, verbose_name='Primeiro Nome'),
        ),
        migrations.AddField(
            model_name='jogadores',
            name='ultimo_nome',
            field=models.CharField(blank=True, max_length=50, verbose_name='Ultimo Nome'),
        ),
    ]
