# Generated by Django 2.1.3 on 2018-11-27 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot_facebook', '0002_auto_20181127_1120'),
    ]

    operations = [
        migrations.AddField(
            model_name='jogadores',
            name='status',
            field=models.IntegerField(blank=True, choices=[(0, 'Cadastrando'), (1, 'Escolhendo Aventura'), (2, 'Criando Personagem'), (3, 'Jogando Aventura')], default=0, verbose_name='Status'),
        ),
    ]
