# Generated by Django 2.1.3 on 2018-11-27 15:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20181127_1024'),
        ('bot_facebook', '0003_jogadores_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='jogadores',
            name='aventura_atual',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.Aventura', verbose_name='Aventura Atual'),
        ),
    ]
