# Generated by Django 2.1.3 on 2018-11-28 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot_facebook', '0004_jogadores_aventura_atual'),
    ]

    operations = [
        migrations.AddField(
            model_name='jogadores',
            name='id_facebook',
            field=models.CharField(blank=True, max_length=255, verbose_name='Primeiro Nome'),
        ),
    ]
