# Generated by Django 2.1.3 on 2018-11-28 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot_facebook', '0005_jogadores_id_facebook'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jogadores',
            name='id_facebook',
            field=models.CharField(blank=True, max_length=255, unique=True, verbose_name='Primeiro Nome'),
        ),
    ]
